### ISSUE TITLE
[BUG]: github_team_repository does not accept pre-defined "custom" roles

### ISSUE THREAD

**Issue by Invincibear** [integrations/terraform-provider-github#2498]
### Expected Behavior

I should be able to specify the pre-defined "write" role, but it will 422 fail validation. When manually CURLing the API, you have to change `permission` to `role` for it to not fail 422. It isn't documented, I did it on a hunch and it worked. 

The description implies that I can specify a role, but it doesn't actually work:
[permission](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/team_repository#permission-15) - (Optional) The permissions of team members regarding the repository. Must be one of pull, triage, push, maintain, admin or the name of an existing [custom repository role](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-peoples-access-to-your-organization-with-roles/managing-custom-repository-roles-for-an-organization) within the organisation. Defaults to pull.

### Actual Behavior

422 validation error

### Terraform Version

```
Terraform v1.9.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v3.0.2
+ provider registry.terraform.io/hashicorp/azurerm v4.4.0
+ provider registry.terraform.io/hashicorp/time v0.12.1
+ provider registry.terraform.io/integrations/github v6.4.0
```

### Affected Resource(s)

- github_repository_collaborator
- github_repository_collaborators
- github_team_repository

### Debug Output

```shell
resource "github_team_repository" "some_team_repo" {
  team_id    = github_team.some_team.id
  repository = github_repository.some_repo.name
  permission = "write"
}
```

### Panic Output

```shell
Error: PUT https://api.github.com/organizations/{org}/team/{team}/repos/{owner}/{repo}: 422 Validation Failed []
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stevehipwell** [comment]
@Invincibear https://github.com/github/rest-api-description/issues/564 looks related. You might want to also open an issue at [google/go-github](https://github.com/google/go-github) as this TF provider uses that as the GitHub SDK and without support there it can't be fixed here.

**Comment by stevehipwell** [comment]
This issue isn't stale.

**Comment by wwsean08** [comment]
FYI Having tried this I was able to submit a custom role using the `github_team_repository` resource at this point, so I don't think this issue is still relevant.

**Comment by deiga** [comment]
@Invincibear Would you be able to verify?

**Comment by EliSzBr** [comment]
@deiga 
> [@Invincibear](https://github.com/Invincibear) Would you be able to verify?

I do not know at exactly which version this was fixed - but I can confirm that adding a custom role in 6.11.1 works 👍 

I believe this issue can be closed
