### ISSUE TITLE
[BUG]: Regression in v6.7.0 for `github_actions_organization_secret` produce invalid state

### ISSUE THREAD

**Issue by 0x46616c6b** [integrations/terraform-provider-github#2804]
### Expected Behavior

Plan and apply for `github_actions_organization_secret` should work after upgrading to `6.7.0`.

### Actual Behavior

After updating from `6.6.0` to 6.7.0` nothing should break to my existing `github_actions_organization_secret` resources. The plan produces a diff:

```hcl
  # github_actions_organization_secret.this["NPM_TOKEN"] will be updated in-place
!   resource "github_actions_organization_secret" "this" {
+       destroy_on_drift        = true
        id                      = "NPM_TOKEN"
        # (7 unchanged attributes hidden)
    }
```

and the apply failed with

> **Error: Provider produced inconsistent result after apply**
> When applying changes to github_actions_organization_secret.this["NPM_TOKEN"], provider "provider[\"registry.terraform.io/integrations/github\"]" produced an unexpected new value: Root object was present, but now absent.
> 
> This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Terraform Version

Terraform v1.10.5
on linux_amd64

### Affected Resource(s)

- `github_actions_organization_secret`

### Terraform Configuration Files

```hcl
variable "github_app_id" {
  default = "<REDACTED>"
  type    = string
}

variable "github_app_installation_id" {
  default = "<REDACTED>"
  type    = string
}

variable "github_app_pem_file" {
  type = string
}

provider "github" {
  app_auth {
    id              = var.github_app_id
    installation_id = var.github_app_installation_id
    pem_file        = var.github_app_pem_file
  }

  parallel_requests = true
  write_delay_ms    = 200
}

terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "6.7.0"
    }
  }

  backend "remote" {
    hostname     = "<REDACTED>"
    organization = "<REDACTED>"

    workspaces {
      name = "<REDACTED>"
    }
  }
}
```

### Debug Output

```
2025-10-23T09:08:51.471Z [WARN]  Provider "registry.terraform.io/integrations/github" produced an invalid plan for github_actions_organization_secret.this["NPM_TOKEN"], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .destroy_on_drift: planned value cty.True for a non-computed attribute
      - .plaintext_value: sensitive planned value for a non-computed attribute
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Sending request downstream: @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:22 @module=sdk.proto tf_proto_version=5.6 tf_provider_addr=provider tf_req_id=a444093c-3ab7-d195-e9e2-637e037881c3 tf_resource_type=github_actions_organization_secret tf_rpc=PlanResourceChange timestamp=2025-10-23T09:08:51.467Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Served request: tf_provider_addr=provider tf_req_id=8773c630-21c5-7e2c-1565-9363b8d6f531 tf_resource_type=github_actions_organization_secret @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:734 @module=sdk.proto tf_proto_version=5.6 tf_rpc=ValidateResourceTypeConfig timestamp=2025-10-23T09:08:51.467Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Received request: tf_provider_addr=provider tf_req_id=2f878911-0a52-31d4-020f-34c09d96cecb tf_resource_type=github_actions_organization_secret @module=sdk.proto tf_proto_version=5.6 tf_rpc=PlanResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:811 timestamp=2025-10-23T09:08:51.467Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Announced client capabilities: tf_client_capability_deferral_allowed=true tf_proto_version=5.6 tf_req_id=2f878911-0a52-31d4-020f-34c09d96cecb @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tf5serverlogging/client_capabilities.go:66 @module=sdk.proto tf_resource_type=github_actions_organization_secret tf_rpc=PlanResourceChange tf_provider_addr=provider timestamp=2025-10-23T09:08:51.467Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Sending request downstream: tf_proto_version=5.6 tf_req_id=2f878911-0a52-31d4-020f-34c09d96cecb tf_resource_type=github_actions_organization_secret tf_rpc=PlanResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:22 @module=sdk.proto tf_provider_addr=provider timestamp=2025-10-23T09:08:51.467Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Received downstream response: @module=sdk.proto tf_proto_version=5.6 tf_resource_type=github_actions_organization_secret @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:42 tf_req_duration_ms=0 tf_req_id=a444093c-3ab7-d195-e9e2-637e037881c3 tf_rpc=PlanResourceChange diagnostic_error_count=0 diagnostic_warning_count=0 tf_provider_addr=provider timestamp=2025-10-23T09:08:51.468Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Served request: @module=sdk.proto tf_provider_addr=provider tf_rpc=PlanResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:843 tf_proto_version=5.6 tf_req_id=a444093c-3ab7-d195-e9e2-637e037881c3 tf_resource_type=github_actions_organization_secret timestamp=2025-10-23T09:08:51.468Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Received downstream response: diagnostic_error_count=0 diagnostic_warning_count=0 tf_proto_version=5.6 tf_provider_addr=provider tf_rpc=PlanResourceChange tf_resource_type=github_actions_organization_secret @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:42 @module=sdk.proto tf_req_duration_ms=0 tf_req_id=2f878911-0a52-31d4-020f-34c09d96cecb timestamp=2025-10-23T09:08:51.468Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Served request: tf_proto_version=5.6 tf_req_id=2f878911-0a52-31d4-020f-34c09d96cecb tf_resource_type=github_actions_organization_secret tf_rpc=PlanResourceChange @module=sdk.proto tf_provider_addr=provider @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:843 timestamp=2025-10-23T09:08:51.468Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Received request: @module=sdk.proto tf_proto_version=5.6 tf_req_id=3a145939-cb70-bb78-d71d-deaff3e439f3 tf_resource_type=github_actions_organization_secret @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:811 tf_provider_addr=provider tf_rpc=PlanResourceChange timestamp=2025-10-23T09:08:51.468Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Announced client capabilities: tf_proto_version=5.6 tf_provider_addr=provider tf_req_id=3a145939-cb70-bb78-d71d-deaff3e439f3 tf_resource_type=github_actions_organization_secret @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tf5serverlogging/client_capabilities.go:66 @module=sdk.proto tf_client_capability_deferral_allowed=true tf_rpc=PlanResourceChange timestamp=2025-10-23T09:08:51.468Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Sending request downstream: tf_req_id=3a145939-cb70-bb78-d71d-deaff3e439f3 tf_rpc=PlanResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:22 @module=sdk.proto tf_proto_version=5.6 tf_provider_addr=provider tf_resource_type=github_actions_organization_secret timestamp=2025-10-23T09:08:51.468Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Received request: tf_resource_type=github_actions_organization_secret @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:714 @module=sdk.proto tf_provider_addr=provider tf_rpc=ValidateResourceTypeConfig tf_proto_version=5.6 tf_req_id=5cc31188-ef6d-2f13-e33e-989da3e9a2d4 timestamp=2025-10-23T09:08:51.468Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Sending request downstream: tf_resource_type=github_actions_organization_secret @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:22 tf_proto_version=5.6 tf_provider_addr=provider tf_req_id=5cc31188-ef6d-2f13-e33e-989da3e9a2d4 tf_rpc=ValidateResourceTypeConfig @module=sdk.proto timestamp=2025-10-23T09:08:51.468Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Calling downstream: tf_provider_addr=provider tf_resource_type=github_actions_organization_secret @module=sdk.helper_schema tf_req_id=5cc31188-ef6d-2f13-e33e-989da3e9a2d4 tf_rpc=ValidateResourceTypeConfig @caller=github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:287 timestamp=2025-10-23T09:08:51.468Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Received request: tf_provider_addr=provider tf_req_id=df1cf398-3930-01ba-221c-76b4f76dd5e3 tf_rpc=PlanResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:811 @module=sdk.proto tf_proto_version=5.6 tf_resource_type=github_actions_organization_secret timestamp=2025-10-23T09:08:51.468Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Announced client capabilities: tf_req_id=df1cf398-3930-01ba-221c-76b4f76dd5e3 tf_resource_type=github_actions_organization_secret @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tf5serverlogging/client_capabilities.go:66 @module=sdk.proto tf_client_capability_deferral_allowed=true tf_proto_version=5.6 tf_provider_addr=provider tf_rpc=PlanResourceChange timestamp=2025-10-23T09:08:51.468Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Sending request downstream: @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:22 tf_provider_addr=provider tf_req_id=df1cf398-3930-01ba-221c-76b4f76dd5e3 @module=sdk.proto tf_proto_version=5.6 tf_resource_type=github_actions_organization_secret tf_rpc=PlanResourceChange timestamp=2025-10-23T09:08:51.469Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Received downstream response: tf_rpc=PlanResourceChange @module=sdk.proto tf_proto_version=5.6 diagnostic_error_count=0 diagnostic_warning_count=0 tf_provider_addr=provider tf_req_duration_ms=1 tf_req_id=3a145939-cb70-bb78-d71d-deaff3e439f3 @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:42 tf_resource_type=github_actions_organization_secret timestamp=2025-10-23T09:08:51.470Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Served request: tf_provider_addr=provider tf_resource_type=github_actions_organization_secret tf_rpc=PlanResourceChange @module=sdk.proto tf_proto_version=5.6 tf_req_id=3a145939-cb70-bb78-d71d-deaff3e439f3 @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:843 timestamp=2025-10-23T09:08:51.470Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Received request: tf_req_id=5f570286-eb84-2890-d7d8-1c61222e105e tf_resource_type=github_actions_organization_secret tf_provider_addr=provider tf_rpc=PlanResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:811 @module=sdk.proto tf_proto_version=5.6 timestamp=2025-10-23T09:08:51.470Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Announced client capabilities: @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tf5serverlogging/client_capabilities.go:66 @module=sdk.proto tf_client_capability_deferral_allowed=true tf_proto_version=5.6 tf_provider_addr=provider tf_req_id=5f570286-eb84-2890-d7d8-1c61222e105e tf_resource_type=github_actions_organization_secret tf_rpc=PlanResourceChange timestamp=2025-10-23T09:08:51.470Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Sending request downstream: tf_proto_version=5.6 tf_resource_type=github_actions_organization_secret @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:22 @module=sdk.proto tf_provider_addr=provider tf_req_id=5f570286-eb84-2890-d7d8-1c61222e105e tf_rpc=PlanResourceChange timestamp=2025-10-23T09:08:51.470Z
2025-10-23T09:08:51.472Z [TRACE] provider.terraform-provider-github_v6.7.0: Received downstream response: @module=sdk.proto diagnostic_error_count=0 diagnostic_warning_count=0 tf_provider_addr=provider tf_req_duration_ms=0 @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:42 tf_rpc=PlanResourceChange tf_resource_type=github_actions_organization_secret tf_proto_version=5.6 tf_req_id=5f570286-eb84-2890-d7d8-1c61222e105e timestamp=2025-10-23T09:08:51.471Z
2025-10-23T09:08:51.473Z [TRACE] GRPCProvider: GetProviderSchema
2025-10-23T09:08:51.473Z [TRACE] GRPCProvider: returning cached schema: EXTRA_VALUE_AT_END=registry.terraform.io/integrations/github
```

### Panic Output

No panic in output

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @0x46616c6b Looks like we missed a schema migration for this resource so that state get's updated.  Let me work up a patch and get it released.   Apologies for the trouble.

**Comment by nickfloyd** [comment]
Patch release: https://github.com/integrations/terraform-provider-github/releases/tag/v6.7.1

**Comment by evanrappe** [comment]
I don't see this `destroy_on_drift` field documented anywhere. Am I missing it?

**Comment by nickfloyd** [comment]
> I don't see this `destroy_on_drift` field documented anywhere. Am I missing it?

Hey @evanrappe You are correct.  It looks like we forgot to update the docs.  Here's a [PR](https://github.com/integrations/terraform-provider-github/pull/2825) that adds the doc.

**Comment by grimm26** [comment]
I still get the same error with 6.7.1

**Comment by nickfloyd** [comment]
> I still get the same error with 6.7.1

Hey @grimm26 Would you mind posting your debug output so that I can dig in further.

**Comment by AndrewUnderwoodAtFanatics** [comment]
I'm in the same situation as @grimm26, v6.7.0 introduced an inconsistent state bug for `github_actions_organization_secret` objects and it's still occurring on v6.7.1.

**Comment by gunnarvelle** [comment]
This is still an issue in 6.7.1. Please reopen.

**Comment by gunnarvelle** [comment]
> This is still an issue in 6.7.1. Please reopen.

I managed to get around it by specifying `destroy_on_drift = false` on all my github_actions_organization_secret, and thus make the state consistent with the configuration.

**Comment by grimm26** [comment]
> > I still get the same error with 6.7.1
> 
> Hey [@grimm26](https://github.com/grimm26) Would you mind posting your debug output so that I can dig in further.

https://gist.github.com/grimm26/feaad78d68efbd23168843a6822f4d6a

**Comment by nickfloyd** [comment]
Looks like based on the log and going back through the logic that [this](https://github.com/integrations/terraform-provider-github/blob/main/github/resource_github_actions_secret.go#L161) might be the source of the issue.  It looks like `updated_at` only gets updated conditionally and it really should be always be updated to avoid repeat drift detection.

**Basically**:
1. The secret value is updated via GitHub UI
2. Then the provider detects timestamp mismatch and logs "The secret AUTOMATION_TOKEN has been externally updated in GitHub"
3. The provider clears the resource ID to trigger recreation
4. The `updated_at` field in state is not updated to match the new timestamp
5. Next run, the same drift detection triggers again because timestamps still don't match

@grimm26 I'd love another pair of eyes on my assumption through if you or else anyone has time. I believe we're going to have the same [issue](https://github.com/integrations/terraform-provider-github/pull/2832) here as well.

**Comment by nickfloyd** [comment]
Here's the PR with the patch for both secrets - https://github.com/integrations/terraform-provider-github/pull/2832 that I'd like to patch in to v6.7.1 > v6.7.2

Here's the [diff](https://github.com/integrations/terraform-provider-github/compare/v6.7.1-patch...v6.7.2-patch?expand=1) between patches.

**Comment by evanrappe** [comment]
anyone else still see this issue? I created a test secret on v5.45 and then tried to apply the default value here on v6.7.3 and it errored out
```
Terraform will perform the following actions:

  # github_actions_organization_secret.EVAN_TEST will be updated in-place
  ~ resource "github_actions_organization_secret" "EVAN_TEST" {
      + destroy_on_drift        = true
        id                      = "EVAN_TEST"
        # (7 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

github_actions_organization_secret.EVAN_TEST: Modifying... [id=EVAN_TEST]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to github_actions_organization_secret.EVAN_TEST, provider
│ "provider[\"registry.terraform.io/integrations/github\"]" produced an unexpected new value: Root
│ object was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by nickfloyd** [comment]
> anyone else still see this issue? I created a test secret on v5.45 and then tried to apply the default value here on v6.7.3 and it errored out

Hey @evanrappe sorry you're having some trouble here.  So far we've only got confirmation that v6.7.3 is working for others.

Would you mind posting debug logs so that I can dig in further.

**Comment by krisalyssa** [comment]
@nickfloyd We're seeing the same error message with v6.7.3.

[01K8W9878JE1MAFKMDCK4YBTR3-APPLYING-5.txt](https://github.com/user-attachments/files/23263046/01K8W9878JE1MAFKMDCK4YBTR3-APPLYING-5.txt)

**Comment by nickfloyd** [comment]
@krisalyssa I just went through your log.  I feel strongly based on my comments [here](https://github.com/integrations/terraform-provider-github/issues/2843#issuecomment-3470377145) that this [patch](https://github.com/integrations/terraform-provider-github/compare/v6.7.3...v6.7.4-patch) will get things sorted for you. Apologies for the trouble, I'm trying to get the patch out there today after I do more testing and validation.

cc: @evanrappe

**Comment by nickfloyd** [comment]
After a lot of testing, validation, and discussion with @stevehipwell ❤️ I have released [v6.7.4](https://github.com/integrations/terraform-provider-github/releases/tag/v6.7.4) with the fixes for this issue.  Please let me know if you run into any issues.

**Comment by krisalyssa** [comment]
@nickfloyd This seems to have resolved our issue. Thanks!

**Comment by evanrappe** [comment]
Is it expected that this adding this field (not changing the value) will trigger a resource recreation? Created this secret via v5.45 freshly again, then upgraded the provider to v6.7.5 and this is the resulting plan: 

```
Terraform will perform the following actions:

  # github_actions_organization_secret.EVAN_TEST must be replaced
-/+ resource "github_actions_organization_secret" "EVAN_TEST" {
      ~ created_at              = "2025-11-03 21:32:57 +0000 UTC" -> (known after apply)
      + destroy_on_drift        = true # forces replacement
      ~ id                      = "EVAN_TEST" -> (known after apply)
      - selected_repository_ids = [] -> null
      ~ updated_at              = "2025-11-03 21:36:37 +0000 UTC" -> (known after apply)
        # (4 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

**Comment by evanrappe** [comment]
@nickfloyd I am still seeing the same behavior I saw on v6.7.3, on v6.8.0. 

Again I created a fresh org secret from fresh TF state on v5.45.0 and attempted to apply the `destroy_on_drift` default value from v6.8.0 and I get the same error from before:

```
Terraform will perform the following actions:

  # github_actions_organization_secret.EVAN_TEST will be updated in-place
  ~ resource "github_actions_organization_secret" "EVAN_TEST" {
      + destroy_on_drift        = true
        id                      = "EVAN_TEST"
        # (7 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

github_actions_organization_secret.EVAN_TEST: Modifying... [id=EVAN_TEST]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to github_actions_organization_secret.EVAN_TEST, provider
│ "provider[\"registry.terraform.io/integrations/github\"]" produced an unexpected new
│ value: Root object was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue
│ tracker.
╵

**Comment by nickfloyd** [comment]
Thanks for reaching back out! This is being discussed [here](https://github.com/integrations/terraform-provider-github/issues/2843#issuecomment-3528552757).
